# Generated by Django 3.1.7 on 2022-12-01 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanager', '0003_auto_20221013_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=350)),
                ('staff_id', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=350, null=True)),
                ('details', models.CharField(blank=True, max_length=350, null=True)),
                ('cost', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('signature', models.CharField(blank=True, max_length=150, null=True)),
                ('issued', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicemanager.book')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='details',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='signature',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
