# Generated by Django 3.1.7 on 2022-12-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanager', '0004_auto_20221201_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docservice',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issue',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
