# Generated by Django 3.1.7 on 2022-12-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('servicemanager', '0006_auto_20221201_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='docservice',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docservice',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.department'),
        ),
    ]
