# Generated by Django 3.1.7 on 2022-12-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanager', '0007_auto_20221201_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docservice',
            name='issued',
        ),
        migrations.RemoveField(
            model_name='docservice',
            name='issued_at',
        ),
        migrations.AddField(
            model_name='docservice',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docservice',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
