# Generated by Django 3.1.7 on 2022-12-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanager', '0008_auto_20221201_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docservice',
            old_name='employee',
            new_name='name',
        ),
    ]
