# Generated by Django 3.1.7 on 2022-12-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanager', '0009_auto_20221201_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docservice',
            name='service_type',
            field=models.CharField(max_length=350),
        ),
    ]
